# https://codeup.kr/problem.php?id=2128&rid=0
# 2128 : 집합은 a, b를 싫어해
1: 1.py 1.data
	#python3 -m memory_profiler ./1.py --debug < ./1.data
	echo "10000000000000000000000000 100 1" | python3 1-lowMem3.py

